language: python
python:
  - "3.6"
script: nosetests -v
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/55c479d5714b2ea72862
    on_success: always
    on_failure: always
    on_start: never
