language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install .
script: pytest -v
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/55c479d5714b2ea72862
    on_success: always
    on_failure: always
    on_start: never
