language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5"
install:
  - pip install -r requirements-dev.txt
  - pip install .
script: make test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/55c479d5714b2ea72862
    on_success: always
    on_failure: always
    on_start: never
