# Copyright (c) 2011-2012 Benjamin Althues <benjamin@babab.nl>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

import datetime
from os.path import expanduser

from dispass import versionStr

class Parse:
    '''Labelfile parser'''

    file_found = False
    '''Boolean value set on init'''

    file_location = None
    '''Sting set on init'''

    file_stripped = []
    '''Labelfile stripped for parsing'''

    labels = None
    '''Dict of `{label: length}`'''

    default_length = 30
    '''Default passphrase length'''

    default_hashname = 'dispass1'
    '''Name of hash to use as default'''

    def __init__(self, file_location='~/.dispass'):
        '''Open file and strip empty lines and comments'''

        try:
            filehandle = open(expanduser(file_location), 'r')
            self.file_found = True
        except IOError:
            self.file_found = False
            self.file_location = file_location
            return

        for i in filehandle:
            if i[0] != '\n' and i[0] != '#':
                self.file_stripped.append(i)

        filehandle.close()

        if self.file_found:
            self.parse()

    def parse(self):
        '''Strip spaces and create list of labels with their options'''

        labels = []
        labels_dispass1 = []

        for i in self.file_stripped:
            wordlist = []
            line = i.rsplit(' ')
            for word in line:
                if word != '':
                    wordlist.append(word.strip('\n'))
            labels.append(wordlist)

        for label in labels:
            labelname = label.pop(0)
            length = self.default_length
            # hashname = self.default_hashname

            for i in label:
                if 'length=' in i:
                    length = int(i.strip('length='))
                # elif 'hash=' in i:
                #     hashname = i.strip('hash=')

            labels_dispass1.append((labelname, length))

        self.labels = dict(labels_dispass1)

        return self

class Write:
    '''Labelfile editor'''

    file_found = False
    '''Boolean value set on init'''

    file_location = None
    '''Sting set on init'''

    def __init__(self, file_location='~/.dispass'):
        '''Open file and strip empty lines and comments'''

        p = Parse()
        self.parsed = p.labels

        try:
            self.filehandle = open(expanduser(file_location), 'r+')
            self.file_found = True
            self.file_location = file_location
        except IOError:
            self.file_found = False
            self.file_location = file_location
            return

    def save(self):
        label_list = []
        for label, length in self.parsed.iteritems():
            label_list.append(label)
            divlen = len(max(label_list, key=len)) + 2

        config = '# Generated by %s on %s\n\n' % \
                (versionStr, datetime.datetime.now())
        for label, length in self.parsed.iteritems():
            config += "{:{fill}} length={}\n".format(label, length,
                                                     fill=divlen)
        self.filehandle.write(config)
        self.filehandle.close()
        print 'Saved to %s' % self.file_location

if __name__ == '__main__':
    w = Write()
    w.save()
