#!/usr/bin/env python
# vim: set et ts=4 sw=4 sts=4:

# Copyright (c) 2012-2014  Tom Willemse <tom@ryuslash.org>
# Copyright (c) 2011-2014  Benjamin Althues <benjamin@babab.nl>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

import exceptions

from dispass.gui import GUI
from dispass.dispass import Settings
from dispass.filehandler import Filehandler

if __name__ == '__main__':
    try:
        settings = Settings()
        gui = GUI(settings, Filehandler(settings))
        gui.mainloop()
    except ImportError:
        print ('Could not find Tkinter, this is a package needed for using\n'
               'the graphical version of dispass.\n'
               'To install, search for a python-tk package for your OS.\n'
               'Arch Linux     \t\t# pacman -S python-tk\n'
               'Debian / Ubuntu\t\t# apt-get install python-tk\n'
               'OpenBSD        \t\t# pkg_add -i python-tk')
    except exceptions.KeyboardInterrupt:
        print ('\nOk, bye')
